# Site settings
production: false
cleanurls: true
title: JZT
tagline: A Nostalgic Adventure Game
description: >
    JZT is an homage to ZZT, a DOS-era adventure game, playable right from within your web browser.
    Like its inspiration, JZT is also a game creation platform that will allow anyone to create and share JZT game worlds.
baseurl: ""
url: "http://localhost:4000"

include:
- .htaccess

sass:
    sass_dir: _sass


collections:
  worlds:
    output: true

defaults:
- scope:
    type: worlds
  values:
    layout: world
- scope:
    type: posts
  values:
    layout: post

# Build settings
markdown: kramdown

permalink: /blog/:title
